{
  "stats": {
    "suites": 0,
    "tests": 1,
    "passes": 0,
    "pending": 0,
    "failures": 1,
    "start": "2023-06-19T12:55:20.163Z",
    "end": "2023-06-19T12:55:20.561Z",
    "duration": 398,
    "testsRegistered": 1,
    "passPercent": 0,
    "pendingPercent": 0,
    "other": 0,
    "hasOther": false,
    "skipped": 0,
    "hasSkipped": false
  },
  "results": [
    {
      "uuid": "7c8689e0-a4b7-45bb-9325-5ce9eb77bd05",
      "title": "",
      "fullFile": "cypress.config.js",
      "file": "cypress.config.js",
      "beforeHooks": [],
      "afterHooks": [],
      "tests": [
        {
          "title": "An uncaught error was detected outside of a test",
          "fullTitle": "An uncaught error was detected outside of a test",
          "timedOut": null,
          "duration": 328,
          "state": "failed",
          "speed": null,
          "pass": false,
          "fail": true,
          "pending": false,
          "context": "[\n  {\n    \"title\": \"cypress-mochawesome-reporter-videos\",\n    \"value\": \"cypress.config.js\"\n  },\n  {\n    \"title\": \"cypress-mochawesome-reporter-screenshots\",\n    \"value\": [\n      [\n        {\n          \"title\": \"Failed screenshot\",\n          \"value\": \"\\\\cypress.config.js\\\\An uncaught error was detected outside of a test (failed).png\"\n        }\n      ]\n    ]\n  }\n]",
          "code": "throw err;",
          "err": {
            "message": "ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > process is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.",
            "estack": "ReferenceError: The following error originated from your test code, not from Cypress.\n\n  > process is not defined\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at ./node_modules/ci-info/index.js (webpack:///./node_modules/ci-info/index.js:5:0)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at ./node_modules/is-ci/index.js (webpack:///./node_modules/is-ci/index.js:3:17)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at Object.eval (webpack:///./node_modules/cypress/lib/util.js:12:13)\n    at ./node_modules/cypress/lib/util.js (http://localhost:56020/__cypress/tests?p=cypress.config.js:30754:30)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)\n    at Object.eval (webpack:///./node_modules/cypress/index.js:6:13)\n    at ./node_modules/cypress/index.js (http://localhost:56020/__cypress/tests?p=cypress.config.js:26591:30)\n    at __webpack_require__ (webpack:///webpack/bootstrap:19:0)",
            "diff": null
          },
          "uuid": "e938ae5d-85c9-4687-8088-7302b671484d",
          "parentUUID": "7c8689e0-a4b7-45bb-9325-5ce9eb77bd05",
          "isHook": false,
          "skipped": false
        }
      ],
      "suites": [],
      "passes": [],
      "failures": [
        "e938ae5d-85c9-4687-8088-7302b671484d"
      ],
      "pending": [],
      "skipped": [],
      "duration": 328,
      "root": true,
      "rootEmpty": false,
      "_timeout": 2000
    }
  ],
  "meta": {
    "mocha": {
      "version": "7.0.1"
    },
    "mochawesome": {
      "options": {
        "quiet": false,
        "reportFilename": "mochawesome",
        "saveHtml": false,
        "saveJson": true,
        "consoleReporter": "spec",
        "useInlineDiffs": false,
        "code": true
      },
      "version": "7.1.3"
    },
    "marge": {
      "options": {
        "overwrite": false,
        "html": false,
        "json": true,
        "reportDir": "cypress\\reports\\html\\.jsons"
      },
      "version": "6.2.0"
    }
  }
}